const API_BASE_URL_STORAGE_KEY = 'apiBaseUrl'
const DEFAULT_QUANTITY = 1
const CHECKOUT_UNAVAILABLE_MESSAGE = '商品当前不可购买，请返回首页重新选择'

module.exports = {
  API_BASE_URL_STORAGE_KEY,
  DEFAULT_QUANTITY,
  CHECKOUT_UNAVAILABLE_MESSAGE
}
